//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskStudentManagement.Data_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Task_Student_ManagementEntities : DbContext
    {
        public Task_Student_ManagementEntities()
            : base("name=Task_Student_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Table> Student_Table { get; set; }
        public virtual DbSet<Teacher_Table> Teacher_Table { get; set; }
    
        public virtual ObjectResult<sp_student_Result> sp_student()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_student_Result>("sp_student");
        }
    }
}
